apiVersion: v2
name: ruan
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: mariadb
    version: "7.3.14"
    repository: file://../common/mariadb/v7.3.14
    condition: mariadb.enabled
icon: file://nginx.png